### PR TITLE
[1766][1743][1332] lint and unit-test fix

### LINKED ISSUE #1332: Lint - disable using getattr in the project
### Describe the task. It can be a feature, documentation, etc.

`getattr` makes sense in very few places in our project, and it usually hides other issues.
- inspect/remove all places where it is used 
- put a linter rule in place 

The easiest would be to use `pylint` for instance:

```
[tool.pylint.main]
load-plugins=pylint.extensions.badbuiltin

[tool.pylint.TYPECHECK]
bad-functions=getattr
```

This rule should be activated both with `scripts.sh lint` and `script.sh lint-check` (people running `lint` expect that a success means it will pass `lint-check`)

### Hedgedoc URL, if you are keeping notes, plots, logs in hedgedoc.

_No response_

### Area

- [ ] datasets, data readers, data preparation and transfer
- [ ] model
- [ ] science
- [x] infrastructure and engineering
- [ ] evaluation, export and visualization
- [ ] documentation

### LINKED ISSUE #1743: `./script/actions.sh unit-test` should restore the original venv after execution
### Describe the task. It can be a feature, documentation, etc.

When we run the unit tests, the command `uv sync --extra cpu` is executed.
This removes some GPU-related packages. To restore the original venv configuration, one must currently run `./script/actions.sh sync` manually.

This restoration should happen automatically.

### Hedgedoc URL, if you are keeping notes, plots, logs in hedgedoc.

_No response_

### Area

- [ ] datasets, data readers, data preparation and transfer
- [ ] model
- [ ] science
- [x] infrastructure and engineering
- [ ] evaluation, export and visualization
- [ ] documentation

### LINKED ISSUE #1766: Linting locally and on github yields inconsistent results
### What happened?

Linting  locally and on github can currently yield inconsistent results, e.g. missing init of class member is currently not flagged locally. `./scripts/actions.sh lint` should be a shortcut for the three steps run on github, see the discussion here: https://github.com/ecmwf/WeatherGenerator/pull/1739#issuecomment-3830816695.

### What are the steps to reproduce the bug?

_No response_

### Hedgedoc link to logs and more information. This ticket is public, do not attach files directly.

_No response_

### PR DESCRIPTION
**Pull request by simone99n**
## Description
- With this PR, Linting locally and on github yields the same results. (#1766)
- Removed useless uv sync before running unit-test (#1743)
- Disable `getattr()`, and add support to add more bad-functions (#1332) 
- **NOTE**: the CI linter for this PR fails because of a new check on bad functions already present in the project.
## Issue Number
- Closes #1332 
- Closes #1766 
- Closes #1743 

## Checklist before asking for review

-   [x] I have performed a self-review of my code
-   [x] My changes comply with basic sanity checks:
      - I have fixed formatting issues with `./scripts/actions.sh lint`
      - I have run unit tests with `./scripts/actions.sh unit-test`
      - I have documented my code and I have updated the docstrings.
      - I have added unit tests, if relevant
-   [ ] I have tried my changes with data and code:
      - I have run the integration tests with `./scripts/actions.sh integration-test`
      - (bigger changes) I have run a full training and I have written in the comment the run_id(s): `launch-slurm.py --time 60`
      - (bigger changes and experiments) I have shared a hegdedoc in the github issue with all the configurations and runs for this experiments
-   [ ] I have informed and aligned with people impacted by my change:
    - for config changes: the MatterMost channels and/or a design doc
    - for changes of dependencies: the MatterMost software development channel

### CODE REVIEW

File: scripts/actions.sh [hunk 1]
```diff
@@ -18,29 +18,40 @@ case "$1" in
...
     (
-      cd "$SCRIPT_DIR" || exit 1
-      uv run --no-project --with "ruff==0.12.2" ruff format --target-version py312 \
-        src/ scripts/ packages/ \
-        && \
-      uv run --no-project --with "ruff==0.12.2" \
-        ruff check --target-version py312 \
-        --fix  \
-        src/ scripts/ packages/
+      echo "LINTING WORKFLOW STARTING..."
```
Comment (tjhunter) [inline scripts/actions.sh]: this is not correct. `lint` is here to run the formatting commands, the `-check` are here to ensure that you have run the commands first. The output for example should not mention a reformatting:

```
lint-check...
Installed 1 package in 93ms
1 file reformatted, 102 files left unchanged <-- should not reformat
```

File: scripts/actions.sh [hunk 2]
```diff
@@ -18,29 +18,40 @@ case "$1" in
...
     )
     ;;
   lint-check)
     (
       cd "$SCRIPT_DIR" || exit 1
-      uv run --no-project --with "ruff==0.12.2" ruff format --target-version py312 \
-        -n \
-        src/ scripts/ packages/ \
+      uv run --no-project --with "ruff==0.12.2" \
+      ruff format --target-version py312 -n src/ scripts/ packages/ \
```
Comment (tjhunter) [inline scripts/actions.sh]: make sure to keep the identation. it reads as if there were 2 commands.

File: scripts/check_badfunctions.py [hunk 3]
```diff
@@ -0,0 +1,150 @@
+# ruff: noqa: T201, N802
```
Comment (tjhunter) [inline scripts/check_badfunctions.py]: Instead of making your own code (which is brittle because it will also traverse virtualenvs, etc.), there is a `pylint` plugin (thank you chatgpt). You can activate it this way in pyproject.toml

```
[tool.pylint.main]
ignore = ["tests", ".venv", ".git", ".tox", ".ruff_cache"]
load-plugins = ["pylint.extensions.bad_builtin"]

[tool.pylint.bad_builtins]
bad-functions = ["getattr", "setattr"]

[tool.pylint.messages_control]
disable = ["all"]
enable = ["W0201", "W0141"]

```

**Review by tjhunter — CHANGES_REQUESTED** [review]
@simone99n  thanks for tackling these issues. There is an issue with your logic, let's discuss it.

File: scripts/actions.sh [hunk 4]
```diff
@@ -18,29 +18,40 @@ case "$1" in
...
-        src/ scripts/ packages/ \
-        && \
-      uv run --no-project --with "ruff==0.12.2" \
-        ruff check --target-version py312 \
-        --fix  \
-        src/ scripts/ packages/
+      echo "LINTING WORKFLOW STARTING..."
+      
+      echo "lint-check..."
+      ./scripts/actions.sh lint-check
```
Comment (tjhunter) [inline scripts/actions.sh]: add `&&` chaining to ensure they all run and fail together

File: scripts/actions.sh [hunk 5]
```diff
@@ -18,29 +18,40 @@ case "$1" in
...
+      echo "lint-fix..."
+      ./scripts/actions.sh lint-fix
```
Comment (tjhunter) [inline scripts/actions.sh]: it should not be here?

File: scripts/actions.sh [hunk 6]
```diff
@@ -18,29 +18,40 @@ case "$1" in
...
+      echo "toml-checking..."
+      ./scripts/actions.sh toml-check
+      echo "type-checking..."
+      ./scripts/actions.sh type-check
```
Comment (tjhunter) [inline scripts/actions.sh]: we can leave this one as warning (it should not fail the linting)

File: scripts/check_badfunctions.py (hunk 3 above)
Comment (simone99n) [reply scripts/check_badfunctions.py]: it works!

**Comment by tjhunter** [comment]
@simone99n  let's whitelist these few lines for the time being and fix them later.

**Comment by simone99n** [comment]
@tjhunter done.

**Review by tjhunter — APPROVED** [review]
It is better to put a message such asth #noqa on the lines that are concerned rather than the whole file, because then people can add more problematic code in the meantime in the file. Let's merge for now.
